#importamos la imagen base
FROM python:3.12-slim 

#creamos carpeta de trabajo
WORKDIR /app

#Copiar requerimientos del proyecto
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#Copiar el resto del proyecto
COPY ./app ./app

#Exponer el puerto
EXPOSE 5000

#Comandos para ejecutar FastAPI
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]